### ISSUE TITLE
babel branch does not "refresh" server.

### ISSUE THREAD

**Issue by trollepierre** [adbutterfield/fast-refresh-express#5]
<img width="577" alt="Capture d’écran 2023-06-29 à 17 08 58" src="https://github.com/adbutterfield/fast-refresh-express/assets/8363334/6b3f9e77-84ef-4286-ac61-f3e1c12520a4">

How to reproduce:

1. `git checkout babel`

2. `npm install && npm run dev`

3. Edit "Top.tsx" line 5, change template string `Top` by `FLOP` 

4. Instantanly the website is refreshed :tada: 

5.  F5 / Cmd + R on the website => 💣

**Comment by trollepierre** [comment]
Solution found: cherry-pick each commit from main to babel. 😘

**Comment by adbutterfield** [comment]
Sorry, just saw this issue.

~~What did you cherry-pick to fix it?~~

Found it!
